# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false

install:
  - Rscript -e 'install.packages("lintr")'

script:
  - Rscript -e 'files <- dir("src", full.names = T, recursive = T); for (file in files) { ifelse(!lintr::lint(file)=="", warning(lintr::lint(file)), ) };'
